version: "3"

services:
  laravel:
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker.env:/var/www/.env
    ports:
      - "8000:8000"

    depends_on:
      - mysql
      - redis

  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    ports:
      - "3336:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: dashboard
      MYSQL_ROOT_PASSWORD: root

  mysqllrs:
    image: mysql:5.7
    ports:
      - "3337:3306"
    volumes:
      - ./lrs-dump:/docker-entrypoint-initdb.d
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: lrs
      MYSQL_USER: lrs
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000 # Cube.js API and Developer Playground
      - 3000:3000 # Dashboard app, if created
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - ./cube_conf:/cube/conf
      # Prevent dev dependencies leaking
      - .empty:/cube/conf/node_modules/@cubejs-backend/

